version: '3'
services:
  db:
    image: postgres:14
    container_name: app_db
    volumes:
      - .:/postgres_data/var/lib/postgres/data
    command: "postgres -c 'max_connections=10'"
    environment:
      - POSTGRES_DB=app_database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  app:
    build: .
    container_name: app
    env_file:
      - .env
    volumes:
      - .:/app_data
    ports:
      - 9000:8080
    depends_on:
      - db
